name: rutina_tracker_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  path_provider: ^2.0.11
  permission_handler: ^11.0.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  flutter_local_notifications: ^19.2.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  fl_chart: ^0.64.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_bg_metal.png
    - assets/images/default_profile.png
